package model;

import lombok.Data;

/**
 * Person Lombok
 *
 * <p>Data class representing a person. Getters, setters, {@code equals}, {@code hashCode},
 * {@code toString}, and a required-args constructor are generated by Lombok's {@code @Data}.
 *
 * @author Daniel Appenmaier
 * @version 1.0
 *
 */
@Data
public class PersonLombok {

   private String name;
   private int age;
   private final char dna;

}
